version: "3.3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=note_user
      - MONGO_INITDB_ROOT_PASSWORD=12345678
      - MONGO_INITDB_DATABASE=note_db
    volumes:
      - mongo:/data/db
    networks:
      - mongodb_network
    ports:
      - "27017:27017"

volumes:
  mongo:

networks:
  mongodb_network: