version: "3.3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=note_user
      - MONGO_INITDB_ROOT_PASSWORD=12345678
      - MONGO_INITDB_DATABASE=note_db
    volumes:
      - mongo:/data/db
    networks:
      - mongodb_network
    ports:
      - "27017:27017"

  note-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note_container
    image: note_container
    environment:
      - DB_USERNAME=note_user
      - SWAGGER_SERVER_BASE_URL=http://localhost:8080
      - DB_PASSWORD=12345678
      - DB_NAME=note_db
      - DB_PORT=27017
      - DB_HOST=mongodb
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - mongodb_network

volumes:
  mongo:

networks:
  mongodb_network:
